-d G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Video\NBvideo\impl\gwsynthesis\NBvideo.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Video\NBvideo\src\fpga_project.cst
-cfg G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Video\NBvideo\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
