-d G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Logic\NBLogic\impl\gwsynthesis\NBLogic.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Logic\NBLogic\src\Logic.cst
-cfg G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Logic\NBLogic\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-route_option 1
-correct_hold 1
-route_maxfan 23
