-d G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Logic\NBLogic\impl\gwsynthesis\NBLogic.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Logic\NBLogic\src\Logic.cst
-cfg G:\_Programming\_DOCS\Schematics\ModularNBrain\FPGA\Logic\NBLogic\impl\pnr\device.cfg
-bit
-tr
-ph
-warning_all
-timing
-cst_error
-no_cst_warning
-route_option 2
